# Generated by Django 6.0.6 on 2026-08-13 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('min_altitude', models.IntegerField(default=0)),
                ('max_altitude', models.IntegerField(blank=True, null=True)),
                ('winter_required', models.BooleanField(default=False)),
                ('difficult_trek', models.BooleanField(default=False)),
            ],
        ),
    ]
