# Generated by Django 6.0.6 on 2026-08-13 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0018_travelplan_fitness_level_alter_travelplan_budget_and_more'),
        ('feature', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='guides/')),
                ('bio', models.TextField()),
                ('languages', models.CharField(max_length=300)),
                ('experience_years', models.PositiveIntegerField()),
                ('specialization', models.CharField(max_length=200)),
                ('verified', models.BooleanField(default=False)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrekPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trek_name', models.CharField(max_length=150)),
                ('nationality', models.CharField(max_length=50)),
                ('permit_name', models.CharField(max_length=150)),
                ('fee', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fee_type', models.CharField(choices=[('fixed', 'Fixed'), ('daily', 'Per Day')], max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrekRoutePoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=150)),
                ('altitude', models.PositiveIntegerField()),
                ('distance', models.FloatField(blank=True, null=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.destination')),
            ],
        ),
    ]
