# Generated by Django 6.0.6 on 2026-07-22 08:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0002_destination'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=230)),
                ('duration', models.IntegerField()),
                ('difficulty', models.CharField(max_length=30)),
                ('price', models.IntegerField()),
                ('max_people', models.IntegerField()),
                ('itinerery', models.CharField(max_length=50)),
                ('includes', models.CharField(max_length=50)),
                ('excludes', models.CharField(max_length=50)),
                ('featured_image', models.FileField(upload_to='packages/')),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.destination')),
            ],
        ),
    ]
