# Generated by Django 6.0.6 on 2026-07-22 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0003_package'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='duration',
            field=models.CharField(max_length=30),
        ),
    ]
