# Generated by Django 6.0.6 on 2026-07-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0004_alter_package_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='excludes',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='package',
            name='includes',
            field=models.CharField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='package',
            name='itinerery',
            field=models.CharField(max_length=10000),
        ),
    ]
