# Generated by Django 6.0.6 on 2026-07-24 08:28

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0007_tour_rename_booking_date_booking_travel_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='excludes',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Excludes'),
        ),
        migrations.AlterField(
            model_name='package',
            name='includes',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Includes'),
        ),
        migrations.AlterField(
            model_name='package',
            name='itinerery',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Intinerary'),
        ),
    ]
