# Generated by Django 6.0.6 on 2026-07-25 10:22

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0008_alter_package_excludes_alter_package_includes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='itinerery',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='tour',
            name='price',
        ),
        migrations.AddField(
            model_name='package',
            name='itinerary',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Itinerary'),
        ),
        migrations.AddField(
            model_name='tour',
            name='bookings',
            field=models.ManyToManyField(related_name='tours', to='adminpage.booking'),
        ),
        migrations.AddField(
            model_name='tour',
            name='duration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='package',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminpage.package'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='tour',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('rating', models.PositiveIntegerField()),
                ('comment', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.package')),
            ],
        ),
    ]
