# Generated by Django 6.0.6 on 2026-07-27 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0009_remove_package_itinerery_remove_tour_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booked_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
