# Generated by Django 6.0.6 on 2026-07-28 10:08

import django_ckeditor_5.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0010_alter_booking_booked_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(verbose_name='Description'),
        ),
    ]
