# Generated by Django 6.0.6 on 2026-08-06 15:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0012_gallery'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField()),
                ('travelers', models.PositiveIntegerField()),
                ('budget', models.DecimalField(decimal_places=2, max_digits=10)),
                ('hotel', models.CharField(choices=[('Budget', 'Budget'), ('Standard', 'Standard'), ('Luxury', 'Luxury')], max_length=30)),
                ('transport', models.CharField(choices=[('Flight', 'Flight'), ('Train', 'Train'), ('Bus', 'Bus'), ('Cruise', 'Cruise')], max_length=30)),
                ('meals', models.CharField(choices=[('Breakfast Only', 'Breakfast Only'), ('Half Board', 'Half Board'), ('Full Board', 'Full Board'), ('All Inclusive', 'All Inclusive')], max_length=30)),
                ('special_requests', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpage.destination')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
