# Generated by Django 6.0.6 on 2026-08-12 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0016_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='tour',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tour',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='tours/'),
        ),
    ]
