# Generated by Django 6.0.6 on 2026-08-13 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0017_tour_description_tour_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='travelplan',
            name='fitness_level',
            field=models.CharField(blank=True, choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('challenging', 'Challenging'), ('extreme', 'Extreme')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='budget',
            field=models.CharField(choices=[('budget', 'Budget'), ('standard', 'Standard'), ('premium', 'Premium'), ('luxury', 'Luxury')], max_length=20),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='hotel',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='meals',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='transport',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='travelplan',
            name='travelers',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
