# Generated by Django 6.0.6 on 2026-08-13 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0018_travelplan_fitness_level_alter_travelplan_budget_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GearItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(max_length=100)),
                ('season', models.CharField(choices=[('all', 'All Seasons'), ('spring', 'Spring'), ('summer', 'Summer'), ('autumn', 'Autumn'), ('winter', 'Winter')], default='all', max_length=20)),
                ('min_altitude', models.PositiveIntegerField(default=0)),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('moderate', 'Moderate'), ('difficult', 'Difficult')], default='easy', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('essential', models.BooleanField(default=False)),
            ],
        ),
    ]
