# Generated by Django 6.0.6 on 2026-08-17 06:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpage', '0023_tripinquiry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='guides/')),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('experience', models.CharField(choices=[('1-3', '1–3 Years'), ('4-7', '4–7 Years'), ('8-12', '8–12 Years'), ('13+', '13+ Years')], default='1-3', max_length=20)),
                ('specialization', models.CharField(choices=[('trekking', 'Trekking'), ('mountaineering', 'Mountaineering'), ('cultural', 'Cultural Tours'), ('adventure', 'Adventure'), ('wildlife', 'Wildlife'), ('city', 'City Tours')], default='trekking', max_length=50)),
                ('languages', models.CharField(help_text='Example: Nepali, English, Hindi', max_length=300)),
                ('daily_rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rating', models.DecimalField(decimal_places=1, default=5.0, max_digits=3)),
                ('total_reviews', models.PositiveIntegerField(default=0)),
                ('verified', models.BooleanField(default=False)),
                ('available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GuideBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('number_of_people', models.PositiveIntegerField(default=1)),
                ('message', models.TextField(blank=True, null=True)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('guide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='adminpage.guide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='guide_bookings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
